[package]
name = "cu"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1.0.98"
copper-proc-macros = { path = "../copper-proc-macros" }
clap = { version = "4.5.42", features = ["derive"] }
dunce = "1.0.5"
env_filter = "0.1.3"
log = "0.4.27"
oneshot = "0.1.11"
pathdiff = "0.2.3"
terminal_size = "0.4.2"
unicode-width = { version = "0.2.1", features = ["cjk"] }
which = "8.0.0"

[dependencies.tokio]
version = "1.47.0" 
features = ["io-std", "io-util", "macros", "process", "rt", "sync", "time"]
optional = true

[features]
default = ["full"]
full = [
    "prompt",
    "coroutine-heavy",
    "process"
]
# Utils to show prompt for user input in terminal
prompt = []
# Enable coroutine drivers, which allow interop with async
coroutine = ["dep:tokio"]
# Enable heavy coroutine drived by multi-threaded tokio runtime
coroutine-heavy = ["coroutine", "tokio/rt-multi-thread"]
# Enable spawning child processes
process = ["coroutine"]

# Internally used to document where nightly feature is used
# (in particular, doc_cfg)
nightly = []

[[example]]
name = "print"
required-features = ["prompt"]
