version: '3'

includes:
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true

tasks:
  check:
    cmds:
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: cu
          FEATURES: cli
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: cu
          FEATURES: prompt
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: cu
          FEATURES: prompt,cli
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: cu
          FEATURES: cli,coroutine
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: cu
          FEATURES: fs
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: cu
          FEATURES: process
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: cu
          FEATURES: full
      - task: cargo:fmt-check

  fix:
    cmds:
      - task: cargo:fmt-fix

  dev-doc:
    cmds:
      - task: cargo:watch-serve-doc
        vars:
          CARGO_ARGS: --all-features
          TOOLCHAIN: +nightly

  test:
    cmds:
      - cargo test --doc --features full
