version: '3'

includes:
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true

tasks:
  check:
    cmds:
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: cu
          FEATURES: default
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: cu
          FEATURES: print
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: cu
          FEATURES: cli
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: cu
          FEATURES: prompt
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: cu
          FEATURES: prompt,cli
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: cu
          FEATURES: cli,coroutine
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: cu
          FEATURES: fs
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: cu
          FEATURES: process
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: cu
          FEATURES: parse
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: cu
          FEATURES: json,yaml,toml
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: cu
          FEATURES: full
      - task: cargo:fmt-check
      - cmd: echo "checking default feature"; grep "^default = \[\]$" Cargo.toml

  fix:
    cmds:
      - task: cargo:fmt-fix


  test:
    cmds:
      - cargo test 
      - cargo test --features cli
      - cargo test --features full
