version: '3'

includes:
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true

tasks:
  check:
    cmds:
      - task: cargo:clippy-all
      - task: cargo:fmt-check

  fix:
    cmds:
      - task: cargo:fmt-fix

  dev-doc:
    cmds:
      - task: cargo:watch-serve-doc
        vars:
          CARGO_DOC_ARGS: --no-deps --features full
