version: '3'

includes:
  common:
    taskfile: ./packages/mono-dev/task/common.yaml
    flatten: true
    optional: true

  cu: {taskfile: ./packages/copper, dir: ./packages/copper, internal: true}

tasks:
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - task: common:cargo-binstall
        vars:
          PACKAGES: cargo-watch live-server

  install:
    cmds:
      - task: common:setup-mono-dev-at-packages

  check:
    cmds:
      - task: cu:check

  test:
    cmds:
      - task: cu:test

  doc:
    cmds:
      # note: require nightly toolchain in CI
      - cargo doc --no-deps --all-features
      - cmd: >
          echo "Generating index redirect";
          echo "<!DOCTYPE html>" > target/doc/index.html;
          echo "<html><head>" >> target/doc/index.html;
          echo '<meta http-equiv="refresh" content="0;url=https://pistonight.github.io/cu/cu/">' >> target/doc/index.html;
          echo "</head><body></body></html>" >> target/doc/index.html;
        silent: true
