[package]
name = "cu-proc-macros"
version = "0.1.0"
edition = "2024"
description = "I cannot resist, after trying very hard"
license = "MIT"

[dependencies.pm]
path = "../promethium"
features = ["full"]

[lib]
proc-macro = true
