[package]
name = "copper-proc-macros"
version = "0.1.0"
edition = "2024"
description = "I cannot resist, after trying very hard"
license = "MIT"

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.104", features = ["full"] }

[lib]
proc-macro = true
