name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          mono-dev: packages
          rust: stable
      - run: task exec -- check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          mono-dev: packages
          rust: stable
      - run: task exec -- test
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          mono-dev: packages
          rust: nightly
      - run: task exec -- doc
